Homework2
made-ml-in-prod-2021/n0rdream pull request #3
Opened 2021-05-19 15:41 UTC by N0rdream

В папке src находится библиотека из ДЗ1.
В папке artefacts - pkl-файлы трансформера и модели, необходимые для получения предсказаний.
В папке prediction_request - скрипт для формирования запроса к сервису и его конфиг.
Тесты сервиса двух типов:
- первый через TestClient FastAPI,
- второй поднимает сервис в докер-контейнере и делает запросы через requests.
Выполнял только пункты на 15 баллов, без дополнительных.

2021-05-21 16:09 UTC, asv715 commented
Первое ДЗ тоже тут оказалось. Так и задумано или не от той ветки ответвление произошло?

2021-05-21 16:12 UTC, asv715 commented on online_inference/requirements.txt
> +docker
Точно все эти зависимости нужны в online_inference?

2021-05-21 16:13 UTC, asv715 commented on online_inference/src/data/transformations.py
> +from ..parameters import SplittingParams
Что означают две точки?

2021-05-21 16:16 UTC, asv715 commented on online_inference/src/pipelines/training.py
> +    logger.info(f"start train pipeline with params {params}")
Можешь пояснить назначение функций тренировки модели в данном сервисе?

2021-05-21 16:18 UTC, asv715 commented on online_inference/tests/fixtures/fixtures_docker.py
> +    container.remove(force=True)
Правильно понимаю, что это тесты манипуляций с Докером? Не сталкивался с таким, но выглядит круто

2021-05-23 13:24 UTC, Mikhail-M requested changes
Добейтесь, чтобы не было кода первой дз в этом реквесте

2021-05-29 10:02 UTC, N0rdream commented
> Первое ДЗ тоже тут оказалось. Так и задумано или не от той ветки ответвление произошло?

ДЗ1 удалил

2021-05-29 10:03 UTC, N0rdream commented on online_inference/requirements.txt
> +docker
Удалил ненужное. Разбил зависимости на 3 группы: веб-приложение, скрипт запроса и тестирование

2021-05-29 10:06 UTC, N0rdream commented on online_inference/src/data/transformations.py
> +from ..parameters import SplittingParams
Это переход в родительскую директорию parameters. Аналог "src.parameters". Так сделал для того, чтобы при переименовании "src" во что-нибудь другое не нужно было бы править импорты по всей библиотеке.

2021-05-29 10:09 UTC, N0rdream commented on online_inference/src/pipelines/training.py
> +    logger.info(f"start train pipeline with params {params}")
Задумывалось, что "src" это библиотека типа sklearn, где есть набор различных функциий и классов. Какие-то используются, какие-то нет. Удалил "src", оставил только нужное для онлайн-сервиса в helpers.py.

2021-05-29 10:26 UTC, N0rdream commented on online_inference/tests/fixtures/fixtures_docker.py
> +    container.remove(force=True)
Да, "docker_client.images.build" создает образ, а "docker_client.containers.run" поднимает контейнер. Аналогично как руками делать. Мне так удобно было докер файл проверять и заодно тестировать запросы через requests. Насчет применения в реальных проектах не могу ничего сказать. Видел выступление, где предлагалось таким образом тестировать соединение с реальными базами данными

2021-05-29 10:29 UTC, N0rdream commented
> Добейтесь, чтобы не было кода первой дз в этом реквесте

Удалил библиотеку "src" из первого ДЗ. Функции и классы, без которых сервис работать не будет, перенес в helpers.py.

2021-05-29 10:59 UTC, asv715 commented on online_inference/tests/fixtures/fixtures_docker.py
> +    container.remove(force=True)
Спасибо

2021-05-29 11:00 UTC, asv715 approved these changes
Итог - 15 баллов

2021-05-29 12:04 UTC, Mikhail-M approved these changes
Баллы: 15

За проявленную самодеятельность с докером ничего не снижаем нигде. А вообще в тестах было бы круто готовить модельку в фикстуре или мокать

2021-05-31 08:31 UTC, merged